# Generated by Django 2.1.5 on 2020-11-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_lecturelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollList',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='CODE', max_length=200, null=True)),
                ('memo', models.CharField(blank=True, db_column='MEMO', max_length=500, null=True)),
            ],
            options={
                'db_table': 'enroll_list',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
